version: "3"
services:
  directus:
    image: directus/directus:11.1.0
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
      - config.env
    environment:
      SECRET: "evs-rent-secure-secret-key-2024"
      ADMIN_EMAIL: "admin@gmail.com"
      ADMIN_PASSWORD: "admin123"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:3000"
      ACCESS_TOKEN_TTL: "3600"      
      REFRESH_TOKEN_TTL: "604800"  
      SESSION_TTL: "86400"          